name: html_color_input
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: